name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: foodie_test
          POSTGRES_PASSWORD: 2JoGcxcx8ibZrOdQ9y3zv9cJyB20xkvzwlaRC8Vz
          POSTGRES_PORT: 5432
          POSTGRES_USER: foodie_test
        ports:
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Populate with CNF data
        run: |
          sudo service postgresql start
          psql -h jdbc:postgres -U foodie_test -d foodie_test -c "grant all privileges on database foodie_test to foodie_test;"
          psql -h jdbc:postgres -U foodie_test -d foodie_test -c "grant pg_read_server_files to 'foodie_test';"
          psql -h jdbc:postgres -U foodie_test -d foodie_test -c "\ir scripts/populate_cnf_db.sql;"
      - name: Run tests
        run: sbt test
